// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BlackJack.iOS
{
	public partial class EndGameViewController : UIViewController
	{
		public EndGameViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
